services:
  django_app:
    build: .
    env_file:
      - .env
    command: bash -c "python manage.py collectstatic --noinput && gunicorn setup.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      # - static_vol:/app/setup/static
      # - media_vol:/app/setup/media
      - static_vol:/app/staticfiles
      - media_vol:/app/images
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      # - static_vol:/app/setup/static
      # - media_vol:/app/setup/media
      - static_vol:/app/staticfiles
      - media_vol:/app/images
    ports:
      - "80:80"
    depends_on:
      - django_app

volumes:
  static_vol:
  media_vol:
